### ISSUE TITLE
Aide à la saisie d'input

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#12]
Actuellement : 
Le formulaire n'empèche pas de mettre un nombre de choix invalide (et illogique)

Lorsqu'on clic sur le bouton rien ne se passe

![image](https://github.com/Emmanuel0110/dojo-app/assets/6325757/105ed693-68d3-406e-b91c-9d9c7e34e247)

Comportement désiré : 
* ne pas permettre de saisir un nombre de choix invalide
* afficher un message d'aide

**Comment by pinage404** [comment]
issue à fermer si #13 est fait

**Comment by Emmanuel0110** [comment]
Limited from 1 to 26
