### ISSUE TITLE
Calculer le nombre de sujets en fonction des sujets donnés

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#13]
Actuellement : 
* l'user doit mettre la liste des sujets dans l'input de gauche
* l'user doit compter les sujets et les mettre dans l'input de droite

Comportement désiré :
Calculer le nombre de sujets à partir de la liste

**Comment by Emmanuel0110** [comment]
Le parsing du texte risque d'être coton, non ? Comment savoir si une ligne du texte est un nouveau sujet ou la suite de la description du sujet précédent ? Est-ce qu'on se limite aux listes de sujets bien formatées de notre programming dojo ?

**Comment by pinage404** [comment]
> Est-ce qu'on se limite aux listes de sujets bien formatées de notre programming dojo ?

C'est ton repo, cette décision te revient

> Comment savoir si une ligne du texte est un nouveau sujet ou la suite de la description du sujet précédent ?

Le champ du nombre de sujet pourrait etre pré-remplit par le calcul et corrigeable à la main si besoin

> Le parsing du texte risque d'être coton, non ?

J'imaginais (grossomodo en pseudo code)

```js
textarea.value.trim().split('\n').length
```
