### ISSUE TITLE
Expliciter la préférence dans les choix

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#15]
Contexte : 
Pour les personnes venant pour la première fois, il y a beaucoup d'infos à découvrir (le lieu, l'organisation, les personnes…) ; avec probablement du stresse

On explique les règles de comment voter

Il y a souvent des erreurs

Actuellement : 
Il y a une liste de `select` pour chaque choix possible
![image](https://github.com/Emmanuel0110/dojo-app/assets/6325757/52dff72a-0701-4c80-b2ea-66f5d4bc4ed4)

Idées de solution : 
Ajouter un label "Tes sujets préférés sont :" avant le premier choix ?

Ajouter des coeurs :heart: pour se passer d'explication ?

Ex : 8 sujets > 4 choix
:heart: :heart: :heart: :heart: Choice 1
:heart: :heart: :heart: Choice 2
:heart: :heart: Choice 3
:heart: Choice 4

J'aime bien cette solution car elle est très affordante
Mais s'il y a beaucoup de sujets ça risque d'etre visuellement lourd

**Comment by Emmanuel0110** [comment]
Ou
Favorite subject
2nd favorite subject
3rd favorite subject
...
Qu'en penses-tu?

**Comment by pinage404** [comment]
Le truc qu'il faut arriver à faire comprendre : c'est l'ordre d'importance : le plus haut = le plus important

---

Je n'ai pas d'avis sur cette solution

**Comment by pinage404** [comment]
Pour la solution visuelle et affordante

Peut etre qu'on pourrait limiter les coeurs aux 3 premiers choix

1. les personnes pourront généraliser d'elle meme
2. jusqu'à 9 sujets, c'est ok
3. on a rarement 10 sujets ou plus

Ex : 4 sujets > 2 choix
❤️ ❤️ Choice 1
❤️ Choice 2

Ex : 9 sujets > 4 choix
❤️ ❤️ ❤️ Choice 1
❤️ ❤️ Choice 2
❤️ Choice 3
Choice 4

Ex : 11 sujets > 5 choix
❤️ ❤️ ❤️ Choice 1
❤️ ❤️ Choice 2
❤️ Choice 3
Choice 4
Choice 5

**Comment by Emmanuel0110** [comment]
For now, I just changed "Choice 1" in "Favorite choice"
