### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#19]
## Scénario de reproduction : 
1. Dans le textarea coller les sujets du dernier dojo

```txt

- 9 - A - TicTacToe - Rust - fishbowl - TCR 
- 13 - B - TicTacToe - Python - Mob - TDD 
- 10 - C - Minimal 2D Manhattan distance between two point - Rust - mob 
- 9 - D - Word Ladder - Lisp - Mob - cat -> dog cat->cot->cog->dog
- 7 - E - Traveling Salesman - TS - mob - TDD
- 12 - F - Mysterious Container - Haskell - Mob - TDD (a container without using a data structure) 

```

2. cliquer sur "Generate QR Code"
3. cliquer sur "See results" (sans voter)

## Comportement actuel

une page avec juste le fond d'écran

## Comportement désiré

pas de crash

peut etre un message d'aide indiquant qu'il n'y a eu aucun vote pour le moment

**Comment by pinage404** [comment]
Scénario de reproduction alternatif : 

2.1. flasher le QRCode
2.2. cliquer sur "Submit" (sans faire de choix)

**Comment by Emmanuel0110** [comment]
Done
