### ISSUE TITLE
QRCode plus gros

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#2]
Problème :
Le QRCode est difficile à flasher

Idée de solution :
Idéalement, il faudrait maximiser la taille du QRCode pour que les personnes au fond puissent facilement le flasher

Une taille qui prends presque toute la place disponible serait chouette, en laissant quelques marge au cas où le vidéo projecteur est mal cadré

Quelque chose comme [`width: 95vmin;`](https://developer.mozilla.org/en-US/docs/Web/CSS/length)

**Comment by Emmanuel0110** [comment]
Done

**Comment by pinage404** [comment]
Super, j'ai hate de voir ça en live ! =D
