### ISSUE TITLE
See QRCode -> See Result -> See QRCode

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#21]
## Scénario de reproduction

1. remplir le textarea
2. cliquer sur See QRCode
3. flasher
4. voter
5. cliquer sur See Result

## Comportement actuel

le bouton "See QRCode" est présent

## Interrogation

Est-ce voulu ?

Si oui, pourquoi le résultat des votes est encore affiché ?

**Comment by Emmanuel0110** [comment]
Oui, c'est voulu. C'est pour les gens qui se réveillent au dernier moment "Ah j'avais pas encore scanné le QR-Code"

**Comment by pinage404** [comment]
D'accord

Pourquoi les résultats restent affichés ?

**Comment by Emmanuel0110** [comment]
Ok, done
