### ISSUE TITLE
Lignes vides comptés

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#22]
Depuis cette issue

* #13 

Le nombre de sujets est précalculé (et c'est chouette)

## Scénario de reproduction

![image](https://github.com/Emmanuel0110/dojo-app/assets/6325757/9c1438cb-fdc3-4cd3-93ea-8b0558195414)

1. mettre des lignes vides ou avec des espaces dans les sujets

```txt



A
B
C

D

    
        F

H





```

## Comportement actuel

Les lignes vides sont comptés

## Comportement désiré

Les lignes vides ou avec uniquement des caractères blancs sont ignorées

**Comment by Emmanuel0110** [comment]
Done
