### ISSUE TITLE
Résultats désordonnés

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#23]
Salut,

Lors du dernier dojo, les résultats des votes étaient désordonnées

![coolmaze-shared-content-resized(1)](https://github.com/Emmanuel0110/dojo-app/assets/6325757/f5e780b6-209f-4acb-b205-a0376b2ee511)

Ni triés par nombre de vote, ni triés par ordre alphabétique

(La partie gauche avec les sujets était correcte)

**Comment by Emmanuel0110** [comment]
Ok, je viens de rajouter un tri. Du coup je me demande comment ils étaient ordonnés les semaines précédentes...

**Comment by pinage404** [comment]
il me semble que c'était ordonné par nombre de vote
