### ISSUE TITLE
Un sujet avec 0 vote n'est pas affiché

### ISSUE THREAD

**Issue by marckruzik** [Emmanuel0110/dojo-app#25]
Quand un sujet reçoit 0 vote, il n'est pas affiché dans le graphe avec barres horizontales.
Dans une liste de sujets A B C D E, quand D ne reçoit aucun vote, le graphe affiche seulement A B C E.

Je pense que c'est une erreur et que le sujet avec 0 vote devrait être affiché.

**Comment by Emmanuel0110** [comment]
Bonne remarque ! Voilà, c'est corrigé. Merci
