### ISSUE TITLE
Afficher le nombre de votes en temps réel

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#4]
Problème : 
on ne sait pas quand tout le monde a fini de voter

Demander "qui n'a pas encore voté ?" est souvent innefficace car les personnes sont concentrées à lire les sujets

Besoin : 
Savoir quand le vote est fini

Idée de solution : 
Avoir un compteur avec le nombre de votes qui s'actualise en temps réel (+/- quelques secondes)

Utiliser du [SSE](https://developer.mozilla.org/fr/docs/Web/API/Server-sent_events/Using_server-sent_events) pour actualiser le nombre (sinon WebSocket ou fetch sur un setInterval)

**Comment by Emmanuel0110** [comment]
Fait avec polling pour l'instant

**Comment by pinage404** [comment]
Trop bien =D

Toutes les issues étaient une liste d'idées, pas une liste de devoirs à faire à la maison pour la prochaine session
