### ISSUE TITLE
Afficher la liste des sujets en meme temps que le QRCode

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#5]
Problème :
les personnes mettent du temps à flasher le QRCode pendant que d'autres attendent de voir la liste des sujets

Besoin : 
Ne pas bloquer les gens qui ont besoin du QRCode
Ne pas bloquer les gens qui ont besoin de la liste des sujets

Idée de solutions :
Changer l'input qui demande le nombre de sujets, par un textarea qui prends la liste des sujets

Lorsqu'on affiche le QRCode, les sujets pourraient etre affichés à coté

**Comment by Emmanuel0110** [comment]
Done

**Comment by pinage404** [comment]
Chouette !
