### ISSUE TITLE
Autoriser le scroll sur la page de résultat

### ISSUE THREAD

**Issue by pinage404** [Emmanuel0110/dojo-app#7]
Problème : 
Avec un gros zoom, la liste des résultats sort de l'écran

Besoin :
Voir tout les résultats

Idée de solution : 
Cacher le QRCode qui n'est plus nécessaire à ce moment là

Laisser le comportement par défaut du navigateur qui ajoute une scrollbar si nécessaire

Donc supprimer cette ligne
https://github.com/Emmanuel0110/dojo-app/blob/a0b83207dd0db0348f21f583cb472c6db7d1a7c8/frontend/src/App.css#L10

**Comment by Emmanuel0110** [comment]
Done
